#!/usr/bin/python

import random

def Flipcoin():

    """" Toss a coin and report if heads or tails"""

    toss = random.randrange(1,3)
    
    if toss == 1:
        return "Heads"
    return "Tails"


def main ():
    while True:
        flip = raw_input("Ready to flip? 'q' to quit. ")
        if flip and flip in "Qq":
            break
        print Flipcoin()
    

main()

                         

        
