#!/usr/bin/python
for num in range(10, 0, -1):
    print num,

print '''BLASTOFF!!!'''

for thing in (2, "hat", (0, 1)):
    print thing,
print

for greeting in ("Hi ya Manny", "Hi ya Moe!", "Hi ya Jack!"):
    print greeting

for MIN in range(1, 20, 2):
    print (19-MIN)/2*" ",'*'*MIN

while True:
    answer = raw_input(' What is your name? ')
    try :
        answer = int(answer)
    except ValueError :
        print answer, 'is not a name! Please try again.'
    else :
        break

print "your name is %s" % (answer)
